import '../styles/globals.scss'
import type {AppProps} from 'next/app'
import Head from "next/head";
import { ThemeProvider,  } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import Header from "../components/Header";

import 'macro-css'
import {theme} from "../theme";

export default function App({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>TJ</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=""/>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"/>
      </Head>
      <ThemeProvider theme={theme} >
        <CssBaseline />
        <Header />
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  )
}
